### ISSUE TITLE
nebula图算法集成未来有规划吗？

### ISSUE THREAD

**Issue by imuxuheng** [vesoft-inc/nebula-algorithm#14]
你好，最近在了解关于nebula集成的算法，最新的文档里集成了10种算法，代码里有14种。nebula算法集成未来有什么规划？未来还准备集成哪些算法？有算法集成的清单吗？

**Comment by wey-gu** [comment]
您好，代码库的 master 会比 文档（最新稳定发布版，或者 文档的master）要新一些哈，规划可以看已经有的 issue，如果您希望更多算法被支持，也欢迎给我们提 issue，描述您的需求呢哈

**Comment by imuxuheng** [comment]
首先感谢您的回答。nebula有打算集成最小生成树、图着色、最大流量等相关算法的规划吗？

**Comment by wey-gu** [comment]
@Nicole00, are we going to introduce the following algorithms soon?

- [ ] Minimum spanning Tree algorithm(s)
- [ ] Graph Coloring algorithm(s)
- [ ] Maximum flow algorithm(s)

**Comment by Nicole00** [comment]
> 首先感谢您的回答。nebula有打算集成最小生成树、图着色、最大流量等相关算法的规划吗？

For v3.0.0, these algorithms are not in the plan. We can consider these in the next version.
