### ISSUE TITLE
Doc on remap string id to nonnumeric id

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-algorithm#16]
as title, the gap between nebula core(with string vid support) confuses the user/brings pain to the user.

~~could we support this?~~
As @Nicole00 said in forum, we should document practices on remapping String VID

**Comment by wey-gu** [comment]
ref:https://discuss.nebula-graph.com.cn/t/topic/6246

**Comment by wey-gu** [comment]
examples in https://github.com/vesoft-inc/nebula-algorithm/pull/21 already.

**Comment by Nicole00** [comment]
> examples in #21 already.

Hi, does this issue need to keep open?  if so, please confirm with document student.

**Comment by wey-gu** [comment]
Thanks a lot @Nicole00!
