### ISSUE TITLE
Louvain边节点无法读字符类型

### ISSUE THREAD

**Issue by Amazing1226** [vesoft-inc/nebula-algorithm#18]
![image](https://user-images.githubusercontent.com/94217710/143403532-3b77fe2b-d89b-40bb-8546-f0dfbb691e43.png)
![image](https://user-images.githubusercontent.com/94217710/143403619-f8ee3303-f9f5-4bb4-9f87-907c0c92f828.png)
![image](https://user-images.githubusercontent.com/94217710/143403804-9709270f-d180-443a-8d0a-330c34efe9e5.png)

**Comment by Nicole00** [comment]
jar包提交有以下限制
![image](https://user-images.githubusercontent.com/16240361/143410493-aac28f81-3c5c-4a1e-a001-95482673b216.png)

你api形式调用 可以自己用dense_rank做编码。

**Comment by Nicole00** [comment]
https://github.com/vesoft-inc/nebula-algorithm/blob/master/example/src/main/scala/com/vesoft/nebula/algorithm/PageRankExample.scala
this example gives how to encode the string vid and decode the algorithm result.
