### ISSUE TITLE
现在使用 spark 3.1.2 scala 2.12 我们是否能支持

### ISSUE THREAD

**Issue by mullerhai** [vesoft-inc/nebula-algorithm#32]
您好 ： 从美团过来，发现我们的图数据库很值得称赞，相关的算法库也有了，不过现在在使用 spark 3.1.2 scala 2.12 我们是否能支持

**Comment by Nicole00** [comment]
你好，感谢您的支持和认可。 目前算法库从Nebula读取数据源使用的是Nebula-Spark-Connector，该产品对Spark 3.x的支持也在计划中。

**Comment by mullerhai** [comment]
> 

请问咱有微信群或者钉钉群吗，很多问题反馈不及时？ 另外 nebula 什么时候可以支撑 pure java 方式的批量创建节点和关系，现在只能 importer 和 ngql

**Comment by wey-gu** [comment]
> 

有微信群哈可以加她拉你进群哈。

![image](https://user-images.githubusercontent.com/1651790/148164661-042a620e-1270-4c21-b16c-284e29bf778e.png)

原生 java client 在这里 https://github.com/vesoft-inc/nebula-java

还是 java 原生指的是对象映射？有一个 ORM 的 PR 在这里 https://github.com/vesoft-inc/nebula-java/pull/349

**Comment by wey-gu** [comment]
nebula 的用户论坛很热闹哈，有问题也可以过来搜搜、提问

https://discuss.nebula-graph.com.cn/
