### ISSUE TITLE
louvian outputs fewer vertices

### ISSUE THREAD

**Issue by QingZ11** [vesoft-inc/nebula-algorithm#51]
- version: nebula-algorithm-2.5-20211202.023336-4.jar

**description**:

vertex is a point file with only one column, each represents a point ID, edges is an edge file, the first column is the start point, the second column is the end point, the third column is the weight, with weight calculation, the parameter tol is 500000, the other two The number of iterations parameters are all 10. Are the points in the results inconsistent with the number of points in the original data?

Confirmed that there are no duplicate data.

ref: [https://discuss.nebula-graph.com.cn/t/topic/7640](https://discuss.nebula-graph.com.cn/t/topic/7640)

**Comment by Nicole00** [comment]
https://github.com/vesoft-inc/nebula-algorithm/releases/tag/v2.6.0 already resolved it.
