### ISSUE TITLE
It looks there is no suitable version of nebula-algorithm  for nebula graph 3.2.0

### ISSUE THREAD

**Issue by bithw1** [vesoft-inc/nebula-algorithm#54]
i am reading at https://github.com/vesoft-inc/nebula-algorithm#version-match，it only supports until to version 3.1.X?

It looks there is no suitable version of nebula-algorithm  for nebula graph 3.2.0？

**Comment by Nicole00** [comment]
> i am reading at [https://github.com/vesoft-inc/nebula-algorithm#version-match，it](https://github.com/vesoft-inc/nebula-algorithm#version-match%EF%BC%8Cit) only supports until to version 3.1.X?
> 
> It looks there is no suitable version of nebula-algorithm for nebula graph 3.2.0？

nebula-algorithm 3.0.0 is suitable for NebulaGraph 3.x.
