### ISSUE TITLE
Are there graph algorithms implemented by nebula natively?

### ISSUE THREAD

**Issue by bithw1** [vesoft-inc/nebula-algorithm#55]
I am reading at https://github.com/vesoft-inc/nebula-algorithm, it says, 

> nebula-algorithm is a Spark Application based on [GraphX](https://spark.apache.org/graphx/) with the following Algorithm provided for now

I would ask whether graph algorithm provided by nebula are all based on Spark GraphX， which means，we need to get the data out of nebuba storage to spark graphX engine?

Are there algorithms that are implemented natively by nebula,we means, we don't have to move the data out of nebula storage.

**Comment by wey-gu** [comment]
> I would ask whether graph algorithm provided by nebula are all based on Spark GraphX， which means，we need to get the data out of nebula storage to spark graphX engine?

W: Correct ✅

> Are there algorithms that are implemented natively by nebula, we mean, we don't have to move the data out of nebula storage.

As I know there is only FIND PATH, GET SUBGRAPH call from NebulaGraph natively now, and they are queries more than algorithms, too.

Apart from the NebulaGraph Algorithm(graphx), there is another option for Enterprise/Cloud user, Nebula-Analytics, which is more resource optimal than GraphX and comes with tighter integration(with Explorer, DAG-workflow) to enable Graph OLAP easier, too.

**Comment by bithw1** [comment]
> 
> Apart from the NebulaGraph Algorithm(graphx), there is another option for Enterprise/Cloud user, Nebula-Analytics, which is more resource optimal than GraphX and comes with tighter integration(with Explorer, DAG-workflow) to enable Graph OLAP easier, too.
Thanks @wey-gu for the helpful answer!
I didn't find `Nebula-Analytics` from https://github.com/orgs/vesoft-inc/repositories?page=1&type=all. They are available in Enterprise/Cloud Edition and `not open sourced`?

**Comment by wey-gu** [comment]
You are always welcome @bithw1 , yes, they are not open-sourced yet.

They could be found in docs:

Chinese
- https://docs.nebula-graph.com.cn/3.2.0/graph-computing/nebula-analytics/
- https://docs.nebula-graph.com.cn/3.2.0/graph-computing/use-explorer/

English
- https://docs.nebula-graph.io/3.2.0/graph-computing/nebula-analytics/
- https://docs.nebula-graph.io/3.2.0/graph-computing/use-explorer/

**Comment by QingZ11** [comment]
@bithw1 hi, I have noticed that the issue you created hasn’t been updated for nearly a month, is this issue been resolved? If not resolved, can you provide some more information? If solved, can you close this issue?

Thanks a lot for your contribution anyway 😊
