### ISSUE TITLE
doc: add description and topics of this repo

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-algorithm#59]
Desc:
- Nebula-Algorithm is a Spark Application based on GraphX, which enables state of art Graph Algorithms to run on top of NebulaGraph and write back results to NebulaGraph.

Topics:
- Graph-Database
- Graph-Algorithm
- Spark
- GraphX
- NebulaGraph

Please @Nicole00 help rephrase and when it's OK, please @Shinji-IkariG help edit on the repo :)

Thanks

**Comment by Nicole00** [comment]
Thanks for your thoughtful  consideration. how about `write back results to NebulaGraph`?

**Comment by wey-gu** [comment]
> Thanks for your thoughtful consideration. how about `write back results to NebulaGraph`?

Done :)

**Comment by wey-gu** [comment]
@Shinji-IkariG could you please help update the repo? thanks

**Comment by Shinji-IkariG** [comment]
All Done
