### ISSUE TITLE
Can you add some algorithm descriptions，please

### ISSUE THREAD

**Issue by limingoo** [vesoft-inc/nebula-algorithm#73]
**General Question**

**Comment by QingZ11** [comment]
> algorithm descriptions

You can use Google or Bing, or any other search engine to find the description.

> algorithm demo

ref: https://github.com/vesoft-inc/nebula-algorithm/blob/master/nebula-algorithm/src/test/scala/com/vesoft/nebula/algorithm/lib/ClosenessAlgoSuite.scala

![image](https://github.com/vesoft-inc/nebula-algorithm/assets/38887077/915d38b0-64da-498a-a79a-91a7f1084433)
