### ISSUE TITLE
Shortest path algorithm weights are not valid

### ISSUE THREAD

**Issue by limingoo** [vesoft-inc/nebula-algorithm#74]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

**Your Environments (__required__)**

* OS: `uname -a`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

**Comment by wey-gu** [comment]
@limingoo could you please provide more context/procedure to reproduce where weights are invalid?

**Comment by QingZ11** [comment]
@limingoo I close this issue for the same reason. If you have any new updates, you are welcome to reopen this issue anytime.

Thanks a lot for your contribution anyway 😊
