### ISSUE TITLE
Whether to support custom edge weights

### ISSUE THREAD

**Issue by godlovefei** [vesoft-inc/nebula-algorithm#75]
**Does NebulaGraph-Algorithm not support custom edge weights for graph calculations?**

There is a column of `_rank` in the data currently read from nebula-graphx. I want to use `_rank` as my weight data, but I found that
The initialization of pagerank in the org.apache.spark.graphx.lib.PageRank source code does not use this `_rank` value at all
![image](https://user-images.githubusercontent.com/33597028/233831999-aeb6a380-36ac-492c-ad9f-cee6fb727e75.png)

![image](https://user-images.githubusercontent.com/33597028/233830218-5c7d1a52-9252-4c83-942d-3478e1ad8aa4.png)

Should I need to pass the `_rank` field to customize the weight of the edge?

**Comment by godlovefei** [comment]
Replenish：
![image](https://user-images.githubusercontent.com/33597028/233831944-91ad6155-8e76-4d3e-89f3-0c461f52b93e.png)

**Comment by wey-gu** [comment]
Dear @godlovefei , the `_rank` refer to the NebulaGraph rank for edge, not a normal property named rank.

@Nicole00 is there any way to leverage weight other than the `_rank` of the edge for now?

**Comment by godlovefei** [comment]
> Dear @godlovefei , the `_rank` refer to the NebulaGraph rank for edge, not a normal property named rank.
> 
> @Nicole00 is there any way to leverage weight other than the `_rank` of the edge for now?

No other way has been found yet, because the weight of the edge is initialized in `org.apache.spark.graphx.lib.PageRank`, but I saw that `_rank` can be used as an edge in the `nebula-algorithm` algorithm package weights are used. However, as far as the current situation is concerned, this approach does not seem to work.
![image](https://user-images.githubusercontent.com/33597028/233880852-31220c3f-8739-4928-93fd-437059f90710.png)
