### ISSUE TITLE
nebula引用过低jackson问题

### ISSUE THREAD

**Issue by limingoo** [vesoft-inc/nebula-algorithm#76]
项目使用jackson版本2.11.2
nebula-algorithm版本3.0.0
spark版本2.4.4
scala版本2.11
项目正常启动，
执行任务报错：Incompatible jackson version：2.11.2

尝试：
使用jackson2.9.10版本
项目启动失败：找不到类，com.fasterxml。jackson。databind。json。jsonmapper

**Comment by QingZ11** [comment]
@limingoo hi, I have noticed that the issue you created hasn’t been updated for nearly a month, so I have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime.

Thanks a lot for your contribution anyway 😊
